import assert from 'node:assert/strict';
import fs from 'node:fs';
const worker=fs.readFileSync('src/index.js','utf8');
const core=fs.readFileSync('public/assets/js/global-core.js','utf8');
const flow=fs.readFileSync('public/assets/js/commercial-flow.js','utf8');
const admin=fs.readFileSync('public/assets/js/private-admin.js','utf8');
const page=fs.readFileSync('public/private/admin/index.html','utf8');
const catalog=JSON.parse(fs.readFileSync('public/assets/data/catalog-v1.3.json','utf8'));
assert.match(worker,/INQ-/);
assert.match(worker,/inquiries\/status/);
assert.match(core,/product_specification/);
assert.match(core,/result\.inquiry_id/);
assert.match(flow,/Request this specification/);
assert.match(admin,/admin-inquiry-status/);
assert.match(page,/id="inquiryList"/);
assert.equal(catalog.schemaVersion,'2.0');
for(const p of catalog.products) for(const f of ['faoZone','quality','format','packaging','weights','season','availability','moq','destinationConstraints','documents']) assert.ok(Array.isArray(p[f]),`${p.id} missing ${f}`);
console.log('commercial inquiries pipeline: PASS');