// News journal: bundles the "news" part of tools/editorial/{lang}.json into
// public/assets/js/news-journal-content.js (read by news-current.js) and updates each news page
// (title, description, stylesheets, scripts, body classes).
// Usage: node tools/build-news.cjs
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', 'public');
const LANGS = ['es', 'en', 'fr', 'it', 'ar'];
const VERSION = '20261010-1';
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const content = {};
for (const lang of LANGS) {
  const src = path.join(__dirname, 'editorial', `${lang}.json`);
  if (fs.existsSync(src)) content[lang] = JSON.parse(fs.readFileSync(src, 'utf8')).news;
}
if (!content.es) throw new Error('Spanish content is required');
fs.writeFileSync(path.join(ROOT, 'assets/js/news-journal-content.js'),
  `/* Generated by tools/build-news.cjs from tools/editorial/{lang}.json — edit the JSON, not this file. */\nwindow.ET_NEWS = ${JSON.stringify(content)};\n`);

for (const lang of LANGS) {
  const file = path.join(ROOT, lang === 'es' ? '' : lang, 'news/index.html');
  let html = fs.readFileSync(file, 'utf8');
  const meta = (content[lang] || content.es).meta;
  if (content[lang]) {
    html = html.replace(/<title>[^<]*<\/title>/, `<title>${esc(meta.title)}</title>`)
      .replace(/(<meta name="description" content=")[^"]*(")/, `$1${esc(meta.description)}$2`)
      .replace(/(<meta property="og:title" content=")[^"]*(")/, `$1${esc(meta.title)}$2`)
      .replace(/(<meta property="og:description" content=")[^"]*(")/, `$1${esc(meta.description)}$2`);
  }
  html = html.replace(/<body[^>]*>/, `<body class="news-current news-journal brand-pages" data-lang="${lang}" data-ivory-hero="news">`);
  html = html.replace(/\s*<link rel="stylesheet" href="\/assets\/css\/(?:news-current|news-layer-fix|news-journal|product-heroes)\.css[^"]*"[^>]*>/g, '');
  html = html.replace(/(<link rel="stylesheet" href="\/assets\/css\/header-2026\.css[^"]*"[^>]*>)/,
    `$1\n    <link rel="stylesheet" href="/assets/css/product-heroes.css?v=20261010-2">\n    <link rel="stylesheet" href="/assets/css/news-journal.css?v=${VERSION}">`);
  html = html.replace(/\s*<script src="\/assets\/js\/news-journal-content\.js[^"]*"[^>]*><\/script>/g, '');
  html = html.replace(/<script src="\/assets\/js\/news-current\.js[^"]*" defer><\/script>/,
    `<script src="/assets/js/news-journal-content.js?v=${VERSION}" defer></script>\n    <script src="/assets/js/news-current.js?v=${VERSION}" defer></script>`);
  if (!html.includes('news-journal.css') || !html.includes('news-journal-content.js')) throw new Error(`${lang}: links not inserted`);
  fs.writeFileSync(file, html);
  console.log(lang, content[lang] ? 'ok' : 'ok (Spanish content fallback)');
}
